version: 0.2

env:
  variables:
    AWS_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=${ECR_IMAGE_TAG}
      - REPO_NAME=${ECR_REPOSITORY_NAME}
      - ACCOUNT_ID=${ECR_ACCOUNT_ID}
      - ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

      - echo Retrieving Docker Hub credentials...
      - CREDS=$(aws secretsmanager get-secret-value --secret-id docker-hub-credentials --region $AWS_REGION --query SecretString --output text)
      - DOCKER_USERNAME=$(echo $CREDS | jq -r '.username')
      - DOCKER_PASSWORD=$(echo $CREDS | jq -r '.password')

      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Pulling image from ECR...
      - docker pull $ECR_URI:$IMAGE_TAG

      - echo Tagging image for Docker Hub...
      - docker tag $ECR_URI:$IMAGE_TAG $DOCKER_USERNAME/$REPO_NAME:$IMAGE_TAG

      - echo Pushing image to Docker Hub...
      - docker push $DOCKER_USERNAME/$REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
