name: Kryptic Tha Don Beats App CI/CD Pipeline
# This workflow is triggered on pushes to the 'develop' branch
# It builds a Docker image, scans it for vulnerabilities using Trivy,
# and deploys it to an EKS cluster if the scan passes.
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
    
env:
  REGISTRY_URI: 865494649634.dkr.ecr.us-east-1.amazonaws.com
  REPO_NAME : krypticthadonbeats-dev

jobs:
  Build:
    permissions:
      security-events: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Authenticate to the container registry
    - name: Login to ECR container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_URI }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Build and push Docker image 
      run: |
          echo "Navigating to the application directory"
          cd application
          ls 
          echo "Building and tagging the image with REPO_NAME = ${{ env.REPO_NAME }} & image_tag = ${{ github.sha }}"
          docker build -t ${{ env.REPO_NAME }}:${{ github.sha }} .
           # Tag the Docker image for the Amazon ECR repository using the same GitHub commit SHA
          docker tag ${{ env.REPO_NAME }}:${{ github.sha }} ${{ env.REGISTRY_URI }}/${{ env.REPO_NAME }}:${{ github.sha }}
          # Push the Docker image to the Amazon ECR repository
          echo "Pushing to ${{ env.REGISTRY_URI }} registry"
          docker push ${{ env.REGISTRY_URI }}/${{ env.REPO_NAME }}:${{ github.sha }}

  Container_Scanning:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Authenticate to the container registry
      - name: Login to ECR container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URI }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set Up Docker Scout
        run: | 
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Log in to Docker Hub
        env:
          DOCKER_SCOUT_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: | 
          echo "${DOCKER_SCOUT_HUB_PASSWORD}" | docker login -u "${DOCKER_SCOUT_HUB_USERNAME}" --password-stdin

      - name: Full CVE scan list
        run: docker scout cves ${{ env.REGISTRY_URI }}/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Quickview Scan w/fail conditions 
        run: | 
          docker scout quickview ${{ env.REGISTRY_URI }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} \
            --only-severity critical \
            --exit-code 1